package ch.emf.portedrone.ihm.pc;

import ch.emf.portedrone.beans.Info;
import ch.emf.portedrone.ctrl.ICtrlIhm;
import ch.emf.portedrone.ihm.IIhmCtrl;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;

/**
 * IHM principale de l'application.
 * @author PeclatJ
 */
public class IhmPC extends javax.swing.JFrame implements IIhmCtrl {

    /**
     * Constructeur de l'IHM
     */
    public IhmPC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panInfoMindstorms = new javax.swing.JPanel();
        panRadar = new javax.swing.JPanel();
        radar = new ch.emf.portedrone.ihm.pc.RadarMindstormsPanel();
        lblMindstormsVitesseTexte = new javax.swing.JLabel();
        lblMindstormsBatterieTexte = new javax.swing.JLabel();
        lblMindstormsVitesseValeur = new javax.swing.JLabel();
        lblMindstormsBatterieValeur = new javax.swing.JLabel();
        panCameraDrone = new javax.swing.JPanel();
        cameraDronePanel1 = new ch.emf.portedrone.ihm.pc.CameraDronePanel();
        panInfoDrone = new javax.swing.JPanel();
        lblDroneHauteurTexte = new javax.swing.JLabel();
        lblDroneBatterieTexte = new javax.swing.JLabel();
        lblDroneVitesseTexte = new javax.swing.JLabel();
        lblDroneHauteurValeur = new javax.swing.JLabel();
        lblDroneBatterieValeur = new javax.swing.JLabel();
        lblDroneVitesseValeur = new javax.swing.JLabel();
        lblControleTexte = new javax.swing.JLabel();
        lblControleValeur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panInfoMindstorms.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Mindstorms"));
        panInfoMindstorms.setPreferredSize(new java.awt.Dimension(300, 200));

        panRadar.setBorder(javax.swing.BorderFactory.createTitledBorder("Radar"));

        javax.swing.GroupLayout radarLayout = new javax.swing.GroupLayout(radar);
        radar.setLayout(radarLayout);
        radarLayout.setHorizontalGroup(
            radarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        radarLayout.setVerticalGroup(
            radarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panRadarLayout = new javax.swing.GroupLayout(panRadar);
        panRadar.setLayout(panRadarLayout);
        panRadarLayout.setHorizontalGroup(
            panRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panRadarLayout.setVerticalGroup(
            panRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblMindstormsVitesseTexte.setText("Vitesse");

        lblMindstormsBatterieTexte.setText("Batterie");

        lblMindstormsVitesseValeur.setText("0");

        lblMindstormsBatterieValeur.setText("0");

        javax.swing.GroupLayout panInfoMindstormsLayout = new javax.swing.GroupLayout(panInfoMindstorms);
        panInfoMindstorms.setLayout(panInfoMindstormsLayout);
        panInfoMindstormsLayout.setHorizontalGroup(
            panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoMindstormsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInfoMindstormsLayout.createSequentialGroup()
                        .addGroup(panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMindstormsVitesseTexte)
                            .addComponent(lblMindstormsBatterieTexte))
                        .addGap(18, 18, 18)
                        .addGroup(panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMindstormsBatterieValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMindstormsVitesseValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(166, 166, 166))
                    .addGroup(panInfoMindstormsLayout.createSequentialGroup()
                        .addComponent(panRadar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panInfoMindstormsLayout.setVerticalGroup(
            panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoMindstormsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMindstormsVitesseTexte)
                    .addComponent(lblMindstormsVitesseValeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMindstormsBatterieTexte)
                    .addComponent(lblMindstormsBatterieValeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(panRadar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panCameraDrone.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera Drone"));

        javax.swing.GroupLayout cameraDronePanel1Layout = new javax.swing.GroupLayout(cameraDronePanel1);
        cameraDronePanel1.setLayout(cameraDronePanel1Layout);
        cameraDronePanel1Layout.setHorizontalGroup(
            cameraDronePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cameraDronePanel1Layout.setVerticalGroup(
            cameraDronePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panCameraDroneLayout = new javax.swing.GroupLayout(panCameraDrone);
        panCameraDrone.setLayout(panCameraDroneLayout);
        panCameraDroneLayout.setHorizontalGroup(
            panCameraDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cameraDronePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panCameraDroneLayout.setVerticalGroup(
            panCameraDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cameraDronePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panInfoDrone.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Drone"));
        panInfoDrone.setPreferredSize(new java.awt.Dimension(300, 200));

        lblDroneHauteurTexte.setText("Hauteur");

        lblDroneBatterieTexte.setText("Batterie");

        lblDroneVitesseTexte.setText("Vitesse");

        lblDroneHauteurValeur.setText("0");

        lblDroneBatterieValeur.setText("0");

        lblDroneVitesseValeur.setText("0");

        javax.swing.GroupLayout panInfoDroneLayout = new javax.swing.GroupLayout(panInfoDrone);
        panInfoDrone.setLayout(panInfoDroneLayout);
        panInfoDroneLayout.setHorizontalGroup(
            panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoDroneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInfoDroneLayout.createSequentialGroup()
                        .addComponent(lblDroneHauteurTexte)
                        .addGap(18, 18, 18)
                        .addComponent(lblDroneHauteurValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panInfoDroneLayout.createSequentialGroup()
                        .addComponent(lblDroneVitesseTexte)
                        .addGap(22, 22, 22)
                        .addComponent(lblDroneVitesseValeur, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addGroup(panInfoDroneLayout.createSequentialGroup()
                        .addComponent(lblDroneBatterieTexte)
                        .addGap(18, 18, 18)
                        .addComponent(lblDroneBatterieValeur, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panInfoDroneLayout.setVerticalGroup(
            panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoDroneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDroneHauteurTexte)
                    .addComponent(lblDroneHauteurValeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDroneBatterieTexte)
                    .addComponent(lblDroneBatterieValeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDroneVitesseTexte)
                    .addComponent(lblDroneVitesseValeur))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblControleTexte.setText("Contrôle de :");

        lblControleValeur.setText("Drone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panInfoDrone, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblControleTexte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblControleValeur, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panInfoMindstorms, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panCameraDrone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panCameraDrone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panInfoMindstorms, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panInfoDrone, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblControleTexte)
                            .addComponent(lblControleValeur))
                        .addGap(0, 85, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void afficherMessage(String titre, String message, int type) {
        JOptionPane.showConfirmDialog(this, titre, message, type);
    }

    @Override
    public void setInfo(Info info) {
        lblMindstormsVitesseValeur.setText("G: " + info.infoMindstorms.deplacementMindstorms.vitesseRoueGauche + "D: " + info.infoMindstorms.deplacementMindstorms.vitesseRoueDroite);
        lblMindstormsBatterieValeur.setText("" + info.infoMindstorms.batterie);
        lblDroneHauteurValeur.setText("" + info.infoDrone.hauteur);
        lblDroneBatterieValeur.setText("" + info.infoDrone.hauteur);
        lblDroneVitesseValeur.setText("X: " + info.infoDrone.deplacementDrone.vitesseX + " Y: " + info.infoDrone.deplacementDrone.vitesseY + " Z: " + info.infoDrone.deplacementDrone.vitesseZ + " Spin: " + info.infoDrone.deplacementDrone.spin);

        radar.setEchos(info.infoMindstorms.echo);
        radar.setAngle(info.infoMindstorms.angle);

        repaint();
    }

    @Override
    public void afficherImageDrone(BufferedImage img) {
        cameraDronePanel1.setImg(img);
    }

    @Override
    public void setControleDrone(boolean controleDrone) {
        if(controleDrone) {
            lblControleValeur.setText("Drone");
        } else {
            lblControleValeur.setText("Mindstorms");
        }
    }

    @Override
    public void exit() {
        System.exit(0);
    }
    
    /**
     * Défini le contrôleur de l'IHM.
     * @param ctrl La référence vers le contrôleur,
     */
    public void setCtrl(ICtrlIhm ctrl) {
        this.ctrl = ctrl;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.emf.portedrone.ihm.pc.CameraDronePanel cameraDronePanel1;
    private javax.swing.JLabel lblControleTexte;
    private javax.swing.JLabel lblControleValeur;
    private javax.swing.JLabel lblDroneBatterieTexte;
    private javax.swing.JLabel lblDroneBatterieValeur;
    private javax.swing.JLabel lblDroneHauteurTexte;
    private javax.swing.JLabel lblDroneHauteurValeur;
    private javax.swing.JLabel lblDroneVitesseTexte;
    private javax.swing.JLabel lblDroneVitesseValeur;
    private javax.swing.JLabel lblMindstormsBatterieTexte;
    private javax.swing.JLabel lblMindstormsBatterieValeur;
    private javax.swing.JLabel lblMindstormsVitesseTexte;
    private javax.swing.JLabel lblMindstormsVitesseValeur;
    private javax.swing.JPanel panCameraDrone;
    private javax.swing.JPanel panInfoDrone;
    private javax.swing.JPanel panInfoMindstorms;
    private javax.swing.JPanel panRadar;
    private ch.emf.portedrone.ihm.pc.RadarMindstormsPanel radar;
    // End of variables declaration//GEN-END:variables

    /**
     * La référence vers le contrôleur.
     */
    private ICtrlIhm ctrl;
}
