/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.emf.portedrone.ihm.pc;

import ch.emf.portedrone.beans.Info;
import ch.emf.portedrone.ctrl.ICtrlIhm;
import ch.emf.portedrone.ihm.IIhmCtrl;
import javax.swing.JOptionPane;


/**
 *
 * @author PeclatJ
 */
public class IhmPC extends javax.swing.JFrame implements IIhmCtrl{

    /**
     * Creates new form IhmPC
     */
    public IhmPC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panInfoMindstorms = new javax.swing.JPanel();
        panRadar = new javax.swing.JPanel();
        radar = new ch.emf.portedrone.ihm.pc.RadarMindstormsPanel();
        lblMindstormsVitesseTexte = new javax.swing.JLabel();
        lblMindstormsBatterieTexte = new javax.swing.JLabel();
        lblMindstormsVitesseValeur = new javax.swing.JLabel();
        lblMindstormsBatterieValeur = new javax.swing.JLabel();
        panCameraMindstorms = new javax.swing.JPanel();
        cameraMindstormsPanel1 = new ch.emf.portedrone.ihm.pc.CameraMindstormsPanel();
        panCameraDrone = new javax.swing.JPanel();
        cameraDronePanel1 = new ch.emf.portedrone.ihm.pc.CameraDronePanel();
        panInfoDrone = new javax.swing.JPanel();
        lblDroneHauteurTexte = new javax.swing.JLabel();
        lblDroneBatterieTexte = new javax.swing.JLabel();
        lblDroneVitesseTexte = new javax.swing.JLabel();
        lblDroneHauteurValeur = new javax.swing.JLabel();
        lblDroneBatterieValeur = new javax.swing.JLabel();
        lblDroneVitesseValeur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panInfoMindstorms.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Mindstorms"));
        panInfoMindstorms.setPreferredSize(new java.awt.Dimension(300, 200));

        panRadar.setBorder(javax.swing.BorderFactory.createTitledBorder("Radar"));

        javax.swing.GroupLayout radarLayout = new javax.swing.GroupLayout(radar);
        radar.setLayout(radarLayout);
        radarLayout.setHorizontalGroup(
            radarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        radarLayout.setVerticalGroup(
            radarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panRadarLayout = new javax.swing.GroupLayout(panRadar);
        panRadar.setLayout(panRadarLayout);
        panRadarLayout.setHorizontalGroup(
            panRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panRadarLayout.setVerticalGroup(
            panRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblMindstormsVitesseTexte.setText("Vitesse");

        lblMindstormsBatterieTexte.setText("Batterie");

        lblMindstormsVitesseValeur.setText("0");

        lblMindstormsBatterieValeur.setText("0");

        javax.swing.GroupLayout panInfoMindstormsLayout = new javax.swing.GroupLayout(panInfoMindstorms);
        panInfoMindstorms.setLayout(panInfoMindstormsLayout);
        panInfoMindstormsLayout.setHorizontalGroup(
            panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInfoMindstormsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMindstormsVitesseTexte)
                    .addComponent(lblMindstormsBatterieTexte))
                .addGap(18, 18, 18)
                .addGroup(panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMindstormsBatterieValeur, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(lblMindstormsVitesseValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panRadar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panInfoMindstormsLayout.setVerticalGroup(
            panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoMindstormsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMindstormsVitesseTexte)
                    .addComponent(lblMindstormsVitesseValeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMindstormsBatterieTexte)
                    .addComponent(lblMindstormsBatterieValeur))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panRadar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panCameraMindstorms.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera Mindstorms"));

        javax.swing.GroupLayout cameraMindstormsPanel1Layout = new javax.swing.GroupLayout(cameraMindstormsPanel1);
        cameraMindstormsPanel1.setLayout(cameraMindstormsPanel1Layout);
        cameraMindstormsPanel1Layout.setHorizontalGroup(
            cameraMindstormsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        cameraMindstormsPanel1Layout.setVerticalGroup(
            cameraMindstormsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panCameraMindstormsLayout = new javax.swing.GroupLayout(panCameraMindstorms);
        panCameraMindstorms.setLayout(panCameraMindstormsLayout);
        panCameraMindstormsLayout.setHorizontalGroup(
            panCameraMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cameraMindstormsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panCameraMindstormsLayout.setVerticalGroup(
            panCameraMindstormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cameraMindstormsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panCameraDrone.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera Drone"));

        javax.swing.GroupLayout cameraDronePanel1Layout = new javax.swing.GroupLayout(cameraDronePanel1);
        cameraDronePanel1.setLayout(cameraDronePanel1Layout);
        cameraDronePanel1Layout.setHorizontalGroup(
            cameraDronePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cameraDronePanel1Layout.setVerticalGroup(
            cameraDronePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panCameraDroneLayout = new javax.swing.GroupLayout(panCameraDrone);
        panCameraDrone.setLayout(panCameraDroneLayout);
        panCameraDroneLayout.setHorizontalGroup(
            panCameraDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cameraDronePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panCameraDroneLayout.setVerticalGroup(
            panCameraDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cameraDronePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panInfoDrone.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Drone"));
        panInfoDrone.setPreferredSize(new java.awt.Dimension(300, 200));

        lblDroneHauteurTexte.setText("Hauteur");

        lblDroneBatterieTexte.setText("Batterie");

        lblDroneVitesseTexte.setText("Vitesse");

        lblDroneHauteurValeur.setText("0");

        lblDroneBatterieValeur.setText("0");

        lblDroneVitesseValeur.setText("0");

        javax.swing.GroupLayout panInfoDroneLayout = new javax.swing.GroupLayout(panInfoDrone);
        panInfoDrone.setLayout(panInfoDroneLayout);
        panInfoDroneLayout.setHorizontalGroup(
            panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoDroneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInfoDroneLayout.createSequentialGroup()
                        .addComponent(lblDroneHauteurTexte)
                        .addGap(18, 18, 18)
                        .addComponent(lblDroneHauteurValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panInfoDroneLayout.createSequentialGroup()
                        .addComponent(lblDroneVitesseTexte)
                        .addGap(22, 22, 22)
                        .addComponent(lblDroneVitesseValeur, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                    .addGroup(panInfoDroneLayout.createSequentialGroup()
                        .addComponent(lblDroneBatterieTexte)
                        .addGap(18, 18, 18)
                        .addComponent(lblDroneBatterieValeur, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panInfoDroneLayout.setVerticalGroup(
            panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoDroneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDroneHauteurTexte)
                    .addComponent(lblDroneHauteurValeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDroneBatterieTexte)
                    .addComponent(lblDroneBatterieValeur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInfoDroneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDroneVitesseTexte)
                    .addComponent(lblDroneVitesseValeur))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panInfoMindstorms, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(panInfoDrone, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panCameraDrone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panCameraMindstorms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panInfoMindstorms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panCameraMindstorms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panCameraDrone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(panInfoDrone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void afficherMessage(String titre, String message, int type) {
        JOptionPane.showConfirmDialog(this, titre, message, type);
    }
    
    @Override
    public void setInfo(Info info) {
        lblMindstormsVitesseValeur.setText("G: " + info.infoMindstorms.deplacementMindstorms.vitesseRoueGauche + "D: " + info.infoMindstorms.deplacementMindstorms.vitesseRoueDroite);
        lblMindstormsBatterieValeur.setText("" + info.infoMindstorms.batterie);
        lblDroneHauteurValeur.setText("" + info.infoDrone.hauteur);
        lblDroneBatterieValeur.setText("" + info.infoDrone.hauteur);
        lblDroneVitesseValeur.setText("X: " + info.infoDrone.deplacementDrone.vitesseX + " Y: " + info.infoDrone.deplacementDrone.vitesseY + " Z: " + info.infoDrone.deplacementDrone.vitesseZ + " Spin: " + info.infoDrone.deplacementDrone.spin);
        
        radar.setEchos(info.infoMindstorms.echo);
        radar.setAngle(info.infoMindstorms.angle);
        
        repaint();
    }
    
    @Override
    public void exit() {
        System.exit(0);
    }
    
    public void setCtrl(ICtrlIhm ctrl) {
        this.ctrl = ctrl;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ch.emf.portedrone.ihm.pc.CameraDronePanel cameraDronePanel1;
    private ch.emf.portedrone.ihm.pc.CameraMindstormsPanel cameraMindstormsPanel1;
    private javax.swing.JLabel lblDroneBatterieTexte;
    private javax.swing.JLabel lblDroneBatterieValeur;
    private javax.swing.JLabel lblDroneHauteurTexte;
    private javax.swing.JLabel lblDroneHauteurValeur;
    private javax.swing.JLabel lblDroneVitesseTexte;
    private javax.swing.JLabel lblDroneVitesseValeur;
    private javax.swing.JLabel lblMindstormsBatterieTexte;
    private javax.swing.JLabel lblMindstormsBatterieValeur;
    private javax.swing.JLabel lblMindstormsVitesseTexte;
    private javax.swing.JLabel lblMindstormsVitesseValeur;
    private javax.swing.JPanel panCameraDrone;
    private javax.swing.JPanel panCameraMindstorms;
    private javax.swing.JPanel panInfoDrone;
    private javax.swing.JPanel panInfoMindstorms;
    private javax.swing.JPanel panRadar;
    private ch.emf.portedrone.ihm.pc.RadarMindstormsPanel radar;
    // End of variables declaration//GEN-END:variables

    private ICtrlIhm ctrl;

}


